---
  - hosts: localhost
    tasks:
      - name: Create Blog Database
        postgresql_db: name=blog

      - name: Add Postgres User
        postgresql_user: db=acme name=harrymoreno_backend password=dolores priv=INSERT,SELECT/blog
