---
  - hosts: all
    gather_facts: False
    become: true
    tasks:
      - name: ensure python 2.7 is installed
        raw: apt-get install -y python2.7 python-simplejson

      - name: Create Blog Database
        postgresql_db: name=blog
        with_items:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2

      - name: Add Postgres User
        postgresql_user: db=acme name=harrymoreno_backend password=dolores priv=INSERT,SELECT/blog
